# run this command to fetch env variables from env file and create all required containers
# docker-compose --env-file ./backend/.env up -d

# specify service name if you want to only run specific ones
# docker-compose --env-file ./backend/.env up -d service name

version: "3"
services:
  backend:
    tty: true
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      #connects backend to mongodb container
      - DB_HOST=mongodb
      #JWT_SECRET fetched from .env file in backend
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./frontend/pages:/pages
      - ./frontend/app:/app
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - 27017
    #   link volume for mongodb
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network

volumes:
  #volume for mongodb
  mongodb_data_container:
networks:
  #network linking containers
  app-network:
    driver: bridge
